### ISSUE TITLE
Stackable Cockpit UI MVP

### ISSUE THREAD

**Issue by nightkr** [stackabletech/stackable-cockpit#12]
```[tasklist]
### Tooling setup
- [ ] #3
- [ ] #8
- [ ] https://github.com/stackabletech/stackable/issues/7
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/33
```

```[tasklist]
### Basic functionality
- [ ] https://github.com/stackabletech/stackable/issues/13
- [ ] https://github.com/stackabletech/stackable/issues/14
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/29
- [ ] #38
```

```[tasklist]
### Deployment
- [ ] https://github.com/stackabletech/stackable/issues/17
- [ ] https://github.com/stackabletech/stackable/issues/18
```
```[tasklist]
### Cleanup
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/61
```

**Comment by nightkr** [comment]
Moving some issues into #60 that we had kind of informally downscoped from this ticket a while ago, but never got around to removing from this epic.

**Comment by Techassi** [comment]
The initial MVP is finished. There are a few follow-up epics:

- #62 tracks the implementation of the stacklet create flow
