### ISSUE TITLE
Show list of stacklets (ZooKeepers, HDFS clusters, etc)

### ISSUE THREAD

**Issue by nightkr** [stackabletech/stackable-cockpit#14]
```[tasklist]
### Tasks
- [x] Show basic table
- [ ] Connect table to K8s API
- [ ] Show stacklet status
```

**Comment by lfrancke** [comment]
This is in Done and closed but only one of the items has been checked.
Can you update the ticket?

**Comment by lfrancke** [comment]
@nightkr ping

**Comment by nightkr** [comment]
Sorry, yeah the closing PR should have handled both of those. Updating now.
