### ISSUE TITLE
Tracking: Implement QoL changes for `stackablectl`

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#148]
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/145
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/143
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/142
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/117
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/53
```
