### ISSUE TITLE
feat: Implement progress reporting with third-party tool stdout support

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#153]
Currently, there is no output until the command completes (either successfully or with an error).
Some operations take considerable time and leave the user wondering if anything is happening.

It is possible to set the log level, but that is too verbose for normal operation and is more for debugging.

```[tasklist]
### Tasks
- [ ] Print output as tasks are in progress or complete
- [ ] Add a progress spinner
- [ ] Capture STDOUT/STDERR from Command calls
```
