### ISSUE TITLE
ARM support for stackablectl and cockpit

### ISSUE THREAD

**Issue by fhennig** [stackabletech/stackable-cockpit#200]
As a user with an ARM machine
I want to run stackablectl and the cockpit on my machine
to manage the platform.

```[tasklist]
### Tasks
- [ ] Adapt build pipeline for stackablectl 
- [ ] Test stackablectl and make sure everything works
- [ ] Adapt the cockpit build to support ARM
- [ ] Test if everything works in the cockpit
```

## Acceptance Criteria

- stackablectl is built and published for ARM
- stackablectl works on ARM
- cockpit is built and published for ARM
- cockpit works on ARM

**Comment by fhennig** [comment]
Do we still wanna do this soonish, or rather look into ARM support once the cockpit has more functionality? I'd suggest we punt on this for now

**Comment by sbernauer** [comment]
@Maleware  and I where happy to punt as well. I will remove it from the board, but happy to discuss when anyone thinks we need this now.

**Comment by Maleware** [comment]
As we progressed, I would consider this being done and close it if no one objects.

**Comment by sbernauer** [comment]
I think I would prefer to keep it open (as we don't ship cockpit for ARM AFAIK) but just don't prioritize it :)
But I let you decide
