### ISSUE TITLE
Tracking: feature parity / new features for stackablectl

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#40]
This issue tracks the feature parity of the new stckablectl compared to the current one.

```[tasklist]
### Pull Requests for Feature Parity
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/28
- [ ] Build for all the supported platforms (we might need to vendor openssl)
```

```[tasklist]
### New features
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/35
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/39
- [ ] Add support to uninstall demo
```
```[tasklist]
### Improvements
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/41
```
