### ISSUE TITLE
Improve error, progress and result output

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#59]
Tracked by #40 

```[tasklist]
### Tasks
- [ ] Implement a tracing Layer to automatically display a pretty progress output
- [x] Either use `miette` to pretty print error reports or implement something custom based on `thiserror`.
- [x] Streamline result output
```

```[tasklist]
### Open Questions
- [ ] Can we simplify the result output traits (`ResultOutput` and `TabledOutput`)?
- [ ] Can we combine these traits into one simpler one?
- [ ] Do we move the traits and the implementation into the `stackable` lib?
- [ ] How do we handle if the output should be colored?
```
