### ISSUE TITLE
Tracking: Stacklet Creation Flow

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#62]
```[tasklist]
### Tasks
- [ ] Discuss UX for creation floor
- [ ] Based on above, make adjustments to design and components
- [ ] Integrate flow for two selected products: Kafka and ZooKeeper
- [ ] Integrate i18n into frontend
```

```[tasklist]
### Optional Tasks
- [ ] Add OAuth support (Cockpit is the client), optionally extend to OIDC
- [ ] Automatic generation of creation flow based on CRDs, Rust types or OpenAPI spec (or any combination of these three)
- [ ] Editing deployed/running stacklets
```
