### ISSUE TITLE
Tracking: Release rewritten stackablectl officially using version `1.0.0`

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackable-cockpit#98]
```[tasklist]
### Build on supported platforms
- [ ] Build binary for Linux
- [ ] Build binary for MacOS
- [ ] Build binary for Windows
```

```[tasklist]
### Documentation
- [ ] Add and update documentation
- [ ] Auto generate parts of the documentation (help texts)
```

```[tasklist]
### Release Candidates
- [ ] Release `stackablectl-1.0.0-rc1` in the current state
- [ ] Release `stackablectl-1.0.0-rc2` with #94 (and maybe #85)
- [ ] Release `stackablectl-1.0.0-rc3` with #59
- [ ] Release `stackablectl-1.0.0` when documentation is up-to-date
```

```[tasklist]
### Misc
- [ ] Improve workflows
```
